services:
  nginx:
    build: services/nginx
    container_name: nginx
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/sshd_config:/etc/ssh/sshd_config
      - ./services/www:/var/www
    networks:
      - ft_onion
  tor:
    build: services/tor
    container_name: tor
    volumes:
      - ./services/tor/torrc:/etc/tor/torrc
    networks:
      - ft_onion
    command: tor -f /etc/tor/torrc

networks:
  ft_onion:
    driver: bridge