services:
  inquisitor:
    container_name: inquisitor
    build: ./inquisitor
    privileged: true
    volumes:
      - ./inquisitor/inquisitor.py:/app/inquisitor.py
    networks:
      inquisitor:
        ipv4_address: 10.10.0.101
    mac_address: 00:00:00:00:00:01
    tty: true

  client:
    container_name: ftp_client
    build: ./client
    privileged: true
    networks:
      inquisitor:
        ipv4_address: 10.10.0.102
    mac_address: 00:00:00:00:00:02
    tty: true

  server:
    container_name: ftp_server
    build: ./server
    privileged: true
    volumes:
      - ./server/root:/srv
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
    networks:
      inquisitor:
        ipv4_address: 10.10.0.103
    mac_address: 00:00:00:00:00:03
    tty: true
    cap_add:
      - ALL

networks:
  inquisitor:
    internal: true
    ipam:
      config:
        - subnet: 10.10.0.0/24