servives:
  inquisitor:
    container_name: inquisitor
    build: ./inquisitor
    volumes:
      - ./inquisitor/inquisitor.py:/app/inquisitor.py
      - ./inquisitor/requirements.txt:/app/requirements.txt
    networks:
      - inquisitor
  server:
    container_name: ftp_server
    build: ./server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./server/root:/srv
    environment:
      - FTP_USER=user
      - FTP_PASS=pass
    networks:
      - inquisitor
  client:
    container_name: ftp_client
    build: ./client
    ports:
      - "5800:5800"
    networks:
      - inquisitor

networks:
  inquisitor:
    driver: bridge